### PR TITLE
5812: reviving external_custom target

### LINKED ISSUE #5812: Revive external_custom target
We had created a prototype under the Outreachy project called [Tweetest](https://github.com/adoptium/aqa-tests/wiki/Outreachy-Simplify-and-Gamify-External-Tests-Project:-Tweetest), to be able to more easily extend external tests that meet a certain criteria (those that pull test material from a single repo, and use maven to run their tests).

Related: https://github.com/adoptium/aqa-tests/issues/2076

3 parameters were added to be able to trial out this idea (EXTERNAL_CUSTOM_REPO, EXTERNAL_CUSTOM_BRANCH and EXTERNAL_TEST_CMD which defaults to 'mvn clean install').

This issue is to revive the prototype and verify it works for some sample repositories.  A Grinder job called [Grinder_ext_custom](https://ci.adoptium.net/view/Test_grinder/job/Grinder_ext_custom) has been created with the additional parameters.  A recent run ([Grinder_ext_custom/21](https://ci.adoptium.net/view/Test_grinder/job/Grinder_ext_custom/21)) with the following parameter settings fails in the following way:

EXTERNAL_CUSTOM_REPO=https://github.com/radsz/jacop.git
EXTERNAL_CUSTOM_BRANCH=4.10.0
EXTERNAL_TEST_CMD=mvn --batch-mode clean install

```
12:09:05       [exec] #10 [6/9] COPY jacop/test.sh /test.sh
12:09:05       [exec] #10 ERROR: failed to calculate checksum of ref IOHW:E4VQ:KTS2:COOU:5DLG:NW4B:XV2Z:TFDL:SFRV:IF2C:7NZI:V65O::ppf2jo0abn8pypgbxintwpn3o: "/jacop/test.sh": not found
12:09:05       [exec] 
12:09:05       [exec] #4 [1/9] FROM docker.io/library/eclipse-temurin:11-jdk@sha256:bc9f393dff60292b0e7c10e2d8c5263f404672d5ada65eb38d416616d3593e31
12:09:05       [exec] #4 resolve docker.io/library/eclipse-temurin:11-jdk@sha256:bc9f393dff60292b0e7c10e2d8c5263f404672d5ada65eb38d416616d3593e31 0.1s done
12:09:05       [exec] #4 sha256:bc9f393dff60292b0e7c10e2d8c5263f404672d5ada65eb38d416616d3593e31 7.19kB / 7.19kB done
12:09:06       [exec] #4 CANCELED
12:09:06       [exec] ------
12:09:06       [exec]  > [6/9] COPY jacop/test.sh /test.sh:
12:09:06       [exec] ------
12:09:06       [exec] Dockerfile.hotspot.full:68
12:09:06       [exec] --------------------
12:09:06       [exec]   66 |     
12:09:06       [exec]   67 |     # This is the main script to run jacop tests
12:09:06       [exec]   68 | >>> COPY jacop/test.sh /test.sh
12:09:06       [exec]   69 |     COPY test_base_functions.sh test_base_functions.sh
12:09:06       [exec]   70 |     
12:09:06       [exec] --------------------
12:09:06       [exec] ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref IOHW:E4VQ:KTS2:COOU:5DLG:NW4B:XV2Z:TFDL:SFRV:IF2C:7NZI:V65O::ppf2jo0abn8pypgbxintwpn3o: "/jacop/test.sh": not found
12:09:06  
```

Investigate the failure, and what recent changes to this area of code may have done to affect this target.  Suspect we should be copying from external_custom/test.sh to /test.sh to be able to proceed.

### PR DESCRIPTION
**Pull request by andrlos**
https://github.com/adoptium/aqa-tests/issues/5812 <- whole process documented here...

Close #5812 

should be working with simple one-command-launch cases of external testing

### CODE REVIEW

File: external/dockerfile_functions.sh [hunk 1]
```diff
@@ -611,11 +611,11 @@ generate_dockerfile() {
     base_docker_registry_dir="$9"
     check_external_custom_test=$10
```
Comment (sophia-guo) [inline external/dockerfile_functions.sh:612]: There are three more `check_external_custom_test` in this file and two more in common_functions.sh. Do they need to update to `check_external_custom`?

Comment (andrlos) [reply external/dockerfile_functions.sh:612]: I don't think so.. check_external_custom_test contained a path, whereas check_external_custom contains only binary information whether this path is present (or so is my understanding). I just updated the cases where they are used to test for 0 or 1... The better question would be whether these are ever used.. I can't find a real usage or passing of these variables inside either aqa-tests, nor TKG, they are just assigned, once propagated and then they just die out.. WDYT?

Comment (sophia-guo) [reply external/dockerfile_functions.sh:612]: They should be same thing as binary information.

Comment (andrlos) [reply external/dockerfile_functions.sh]: @sophia-guo okay, this means that the shell script had trouble picking up the 10th argument, and instead picked up the 1st one and appended "0" string.. ${10} solved it..
commit:
https://github.com/adoptium/aqa-tests/commit/73ea24fe236120cfa801c4b7c834f9ed8b1d4fda
grinder
https://ci.adoptium.net/view/Test_grinder/job/Grinder_ext_custom/38/consoleFull

**Review by sophia-guo — APPROVED** [review]

**Review by karianna — APPROVED** [review]
